database:
  node: dc1
  nodes:
    dc1:
      status: 0
      master: 
      slave:
    dc2:
      status: 1
      master: 
      slave:
app:
  env: production
  listen: 3987

redis:
  master:
    address: localhost:6379
    password: ''
    db: 0
  slave:
    fallback_to: master
  cache:
    address: localhost:6379
    password: ''
    db: 10  
      
  slave:
source: ./html

seo:
  title: Home
  canonical: http://www.mataharimall.com
  site: "@MatahariMall.com"
  creator: "@MatahariMall"
  fb_app_id: 109283902183
  fb_admin: 109283902183
  image: http:/127.0.0.1:8080/assets/images/app-icon.png

